# -*- protobuffer -*-
entry {
  target_class: 0
  target_class_string: "multipoint_lock"
}
entry {
  target_class: 1
  target_class_string: "mortice_deadlock"
}
entry {
  target_class: 2
  target_class_string: "automatic_deadlatch"
}
